version: '3'
services:
  php:
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/html

  nginx:
    image: nginx:latest
    ports:
      - "8282:80"
    volumes:
      - ./:/var/www/html/
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
      - './:/usr/share/nginx/html/'
  mysql:
    image: mysql:8
    ports:
      - "33006:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker/mysql/lib:/var/lib/mysql
      - ./docker/mysql/conf.d/my.cnf:/etc/my.cnf
