version: '3'
services:
  php:
    image: php:8.1-fpm
    volumes:
      - ./:/var/www/html

  nginx:
    image: nginx:latest
    ports:
      - "8282:80"
    volumes:
      - './index.php:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
